language: python

python:
  - "3.8.2"
env:
  - SECRET_KEY='TEST'
services:
  - postgresql
install:
  - pip install -r requirements.txt
script:
  - sudo apt-get install gdal-bin
  - python manage.py runserver
